datasets:
  raw:
    sales_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/case_study/sales_data.csv
      driver_params: {}

    product_manufacture_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/case_study/product_manufacturer_list.csv
      driver_params: {}

    google_search_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/case_study/google_search_data.csv
      driver_params: {}

    social_media_data:
      type: ds
      format: xlsx
      uri: ${core.data_base_path}/raw/case_study/social_media_data.csv
      driver_params: {}

    Theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/case_study/Theme_list.csv
      driver_params: {}

    Theme_product_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/case_study/Theme_product_list.csv
      driver_params: {}

  cleaned:
    sales_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/case_study/sales_data.parquet
      driver_params: {}

    product_manufacture_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/case_study/product_manufacture_list.parquet
      driver_params: {}

    google_search_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/case_study/google_search_data.parquet
      driver_params: {}

    social_media_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/case_study/social_media_data.parquet
      driver_params: {}

    Theme_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/case_study/Theme_list.parquet
      driver_params: {}

    Theme_product_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/case_study/Theme_product_list.parquet
      driver_params: {}




  processed:
    sales:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales/sales.parquet
      driver_params: {}

  train:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/sales/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/sales/target.parquet
        driver_params:
          save:
            index: False
  test:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/target.parquet
        driver_params:
          save:
            index: False
  score:
    sales:
      output:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/scored_output.parquet
        driver_params:
          save:
            index: False
